WITH source_data AS (
    SELECT * FROM {{ source('raw', 'claims_portfolio') }}
)
SELECT
    TRIM(record_id) AS record_id,
    TRIM(insured_region) AS insured_region,
    TRIM(insured_branch) AS insured_branch,
    TRIM(reporting_region) AS reporting_region,
    TRIM(claim_reported_by) AS claim_reported_by,
    {{ clean_date('claim_report_date') }} AS claim_report_date,
    TRIM(grouping_code) AS grouping_code,
    TRIM(insurance_type) AS insurance_type,
    TRIM(insurance_class) AS insurance_class,
    TRIM(entity_type) AS entity_type,
    TRIM(taxpayer_id) AS taxpayer_id,
    TRIM(client_name) AS client_name,
    TRIM(injured_party) AS injured_party,
    TRIM(contract_id) AS contract_id,
    TRIM(policy_id) AS policy_id,
    {{ clean_date('incident_date') }} AS incident_date,
    {{ clean_numeric('reported_damage_property') }} AS reported_damage_property,
    {{ clean_numeric('reported_damage_health') }} AS reported_damage_health,
    TRIM(damage_adjustment_notes) AS damage_adjustment_notes,
    TRIM(incident_cause) AS incident_cause,
    TRIM(settlement_order_id) AS settlement_order_id,
    {{ clean_date('settlement_decision_date') }} AS settlement_decision_date,
    {{ clean_date('payout_date') }} AS payout_date,
    {{ clean_numeric('payout_property') }} AS payout_property,
    {{ clean_numeric('payout_health') }} AS payout_health,
    {{ clean_numeric('payout_total') }} AS payout_total,
    TRIM(currency) AS currency,
    {{ clean_date('rejection_date') }} AS rejection_date,
    TRIM(rejection_reason) AS rejection_reason,
    TRIM(claim_id) AS claim_id,
    {{ clean_numeric('claim_expense_amount') }} AS claim_expense_amount,
    {{ clean_numeric('outstanding_loss_amount') }} AS outstanding_loss_amount,
    TRIM(damaged_object) AS damaged_object,
    {{ clean_numeric('recovery_amount') }} AS recovery_amount,
    TRIM(claim_handler) AS claim_handler,
    TRIM(notes) AS notes,
    TRIM(beneficiary) AS beneficiary,
    TRIM(vehicle_engine_type) AS vehicle_engine_type,
    TRIM(branch_name) AS branch_name,
    {{ clean_date('claim_submission_date') }} AS claim_submission_date,
    'Actual' AS scenario,
    NULLIF(TRIM(loaded_at), '')::TIMESTAMP AS loaded_at,
    CURRENT_TIMESTAMP AS updated_at
FROM source_data
