WITH source_data AS (
    SELECT * FROM {{ source('raw', 'reinsurance_outgoing_portfolio') }}
)
SELECT
    id,
    TRIM(seq_number) AS seq_number,
    TRIM(insurance_contract_number) AS insurance_contract_number,
    TRIM(policyholder) AS policyholder,
    TRIM(insurance_type) AS insurance_type,
    TRIM(voluntary_insurance_type) AS voluntary_insurance_type,
    TRIM(mandatory_insurance_type) AS mandatory_insurance_type,
    TRIM(region) AS region,
    TRIM(policyholder_country) AS policyholder_country,
    TRIM(city_village) AS city_village,
    TRIM(individual_legal_entity) AS individual_legal_entity,
    contract_conclusion_date,
    insured_amount_contract,
    TRIM(contract_currency) AS contract_currency,
    insurance_premium_contract,
    TRIM(premium_currency_contract) AS premium_currency_contract,
    contract_start_date,
    contract_end_date,
    insured_amount_policy,
    TRIM(reinsurance_type) AS reinsurance_type,
    insurance_premium_policy,
    TRIM(premium_currency_policy) AS premium_currency_policy,
    insurance_days_count,
    TRIM(reinsurance_broker) AS reinsurance_broker,
    TRIM(reinsurer) AS reinsurer,
    cedant_commission,
    actual_premium_usd_paid_in_uzs,
    actual_premium_eur_paid_in_uzs,
    actual_premium_usd,
    actual_premium_eur,
    actual_premium_rub,
    actual_premium_uzs_net_reinsurance,
    TRIM(premium_currency_policy2) AS premium_currency_policy2,
    total_accrued_premium_uzs,
    premium_accrual_date,
    received_premium_usd,
    received_premium_eur,
    received_premium_rub,
    received_premium_uzs,
    total_received_premium_uzs,
    premium_receipt_date,
    TRIM(policy_number_slip_number) AS policy_number_slip_number,
    insurance_effective_start_date,
    insurance_effective_end_date,
    policy_issue_date_slip_sign_date,
    insurance_duration_days,
    TRIM(notes) AS notes,
    TRIM(bank_name_beneficiary) AS bank_name_beneficiary,
    reinsurer_share_pct,
    TRIM(reinsurer_or_broker_name) AS reinsurer_or_broker_name,
    TRIM(reinsurer_or_broker_country) AS reinsurer_or_broker_country,
    reinsurance_start_date,
    reinsurance_end_date,
    reinsurance_duration_days,
    liabilities_ceded_reinsurance,
    liabilities_ceded_rub,
    liabilities_ceded_eur,
    liabilities_ceded_usd,
    total_premiums_ceded_uzs,
    premiums_ceded_uzs,
    premiums_ceded_usd,
    premiums_ceded_usd_star,
    premiums_ceded_eur_star,
    premiums_ceded_eur,
    premiums_ceded_rub,
    total_commission_received_uzs,
    commission_received_uzs,
    commission_received_usd,
    commission_received_usd_star,
    commission_received_eur_star,
    commission_received_eur,
    commission_received_rub,
    nonresident_tax_usd,
    nonresident_tax_rub,
    nonresident_tax_uzs,
    net_reinsurance_premium_uzs,
    net_reinsurance_premium_rub,
    net_reinsurance_premium_usd_star,
    net_reinsurance_premium_eur,
    net_reinsurance_premium_usd,
    net_reinsurance_premium_transfer_date,
    own_retention,
    income_attribution_date,
    agency_commission,
    agency_commission_pct,
    TRIM(agent_name) AS agent_name,
    acquisition_accrual_date,
    preventive_reserve,
    commission_accrual_date,
    mtpl_preventive_reserve_5pct,
    TRIM(legal_entity_status) AS legal_entity_status,
    assistance_commission,
    TRIM(reinsurance_agreement_number) AS reinsurance_agreement_number,
    reinsurance_agreement_date,
    TRIM(branch) AS branch,
    administrative_expenses,
    base_insurance_premium,
    TRIM(insurance_contract_duration) AS insurance_contract_duration,
    TRIM(blank_col) AS blank_col,
    reporting_date,
    contract_duration_days,
    days_elapsed_since_effective,
    days_remaining_liability,
    days_remaining_liability_calc,
    upr_reinsurer_share,
    ibnr_reinsurer_share,
    TRIM(accounting_group) AS accounting_group,
    upr_reinsurer_share_usd,
    upr_reinsurer_share_eur,
    upr_reinsurer_share_rub,
    ibnr_reinsurer_share_usd,
    ibnr_reinsurer_share_eur,
    ibnr_reinsurer_share_rub,
    'Actual' AS scenario,
    CURRENT_TIMESTAMP AS loaded_at,
    CURRENT_TIMESTAMP AS updated_at
FROM source_data